"""seabreeze.types

common types used to teach mypy about seabreeze
"""
import sys
from typing import Any
from typing import Callable
from typing import Dict
from typing import List
from typing import Type

if sys.version_info >= (3, 9):
    from typing import Protocol
else:
    from typing_extensions import Protocol


class SeaBreezeError(Exception): ...

class SeaBreezeDevice:
    f: "SeaBreezeFeatureAccessor"  # fixme
    is_open: bool
    serial_number: str
    model: str  # fixme
    features: Dict[str, "SeaBreezeFeature"]
    def open(self) -> None: ...
    def close(self) -> None: ...


class SeaBreezeAPI:
    """SeaBreeze API interface"""
    def __init__(self, initialize: bool = True, **_kwargs: Any) -> None: ...
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def add_rs232_device_location(self, device_type: str, bus_path: str, baudrate: int) -> None: ...
    def add_ipv4_device_location(self, device_type: str, ip_address: str, port: int) -> None: ...
    def list_devices(self) -> List[SeaBreezeDevice]: ...
    @staticmethod
    def supported_models() -> List[str]: ...


class SeaBreezeFeature:
    ...


class ListDevicesProtocol(Protocol):
    __call__: Callable[..., List[SeaBreezeDevice]]
    _api: SeaBreezeAPI

def narrow_list_devices_type(func: Any) -> ListDevicesProtocol:
    return func


class SeaBreezeFeatureAccessor(Protocol):
    ...


class SeaBreezeAcquisitionDelayFeature(SeaBreezeFeature): ...
class SeaBreezeContinuousStrobeFeature(SeaBreezeFeature): ...
class SeaBreezeDataBufferFeature(SeaBreezeFeature): ...
class SeaBreezeDHCPServerFeature(SeaBreezeFeature): ...
class SeaBreezeEEPROMFeature(SeaBreezeFeature): ...
class SeaBreezeEthernetConfigurationFeature(SeaBreezeFeature): ...
class SeaBreezeFastBufferFeature(SeaBreezeFeature): ...
class SeaBreezeGPIOFeature(SeaBreezeFeature): ...
class SeaBreezeI2CMasterFeature(SeaBreezeFeature): ...
class SeaBreezeIntrospectionFeature(SeaBreezeFeature): ...
class SeaBreezeIPv4Feature(SeaBreezeFeature): ...
class SeaBreezeIrradCalFeature(SeaBreezeFeature): ...
class SeaBreezeLightSourceFeature(SeaBreezeFeature): ...
class SeaBreezeMulticastFeature(SeaBreezeFeature): ...
class SeaBreezeNetworkConfigurationFeature(SeaBreezeFeature): ...
class SeaBreezeNonlinearityCoefficientsFeature(SeaBreezeFeature): ...
class SeaBreezeNumFeaturesError(SeaBreezeFeature): ...
class SeaBreezeOpticalBenchFeature(SeaBreezeFeature): ...
class SeaBreezePixelBinningFeature(SeaBreezeFeature): ...
class SeaBreezeRawUSBBusAccessFeature(SeaBreezeFeature): ...
class SeaBreezeRevisionFeature(SeaBreezeFeature): ...
class SeaBreezeShutterFeature(SeaBreezeFeature): ...
class SeaBreezeSpectrometerFeature(SeaBreezeFeature): ...
class SeaBreezeSpectrumProcessingFeature(SeaBreezeFeature): ...
class SeaBreezeStrayLightCoefficientsFeature(SeaBreezeFeature): ...
class SeaBreezeStrobeLampFeature(SeaBreezeFeature): ...
class SeaBreezeTemperatureFeature(SeaBreezeFeature): ...
class SeaBreezeThermoElectricFeature(SeaBreezeFeature): ...
class SeaBreezeWifiConfigurationFeature(SeaBreezeFeature): ...


class SeaBreezeBackend:
    """SeaBreeze Backend interface"""
    _backend_: str
    _api_kwargs: Dict[str, Any]

    SeaBreezeAPI: Type[SeaBreezeAPI]
    SeaBreezeDevice: Type[SeaBreezeDevice]
    SeaBreezeError: Type[SeaBreezeError]
    SeaBreezeFeature: Type[SeaBreezeFeature]

    SeaBreezeAcquisitionDelayFeature: Type[SeaBreezeAcquisitionDelayFeature]
    SeaBreezeContinuousStrobeFeature: Type[SeaBreezeContinuousStrobeFeature]
    SeaBreezeDataBufferFeature: Type[SeaBreezeDataBufferFeature]
    SeaBreezeDHCPServerFeature: Type[SeaBreezeDHCPServerFeature]
    SeaBreezeEEPROMFeature: Type[SeaBreezeEEPROMFeature]
    SeaBreezeEthernetConfigurationFeature: Type[SeaBreezeEthernetConfigurationFeature]
    SeaBreezeFastBufferFeature: Type[SeaBreezeFastBufferFeature]
    SeaBreezeGPIOFeature: Type[SeaBreezeGPIOFeature]
    SeaBreezeI2CMasterFeature: Type[SeaBreezeI2CMasterFeature]
    SeaBreezeIntrospectionFeature: Type[SeaBreezeIntrospectionFeature]
    SeaBreezeIPv4Feature: Type[SeaBreezeIPv4Feature]
    SeaBreezeIrradCalFeature: Type[SeaBreezeIrradCalFeature]
    SeaBreezeLightSourceFeature: Type[SeaBreezeLightSourceFeature]
    SeaBreezeMulticastFeature: Type[SeaBreezeMulticastFeature]
    SeaBreezeNetworkConfigurationFeature: Type[SeaBreezeNetworkConfigurationFeature]
    SeaBreezeNonlinearityCoefficientsFeature: Type[SeaBreezeNonlinearityCoefficientsFeature]
    SeaBreezeNumFeaturesError: Type[SeaBreezeNumFeaturesError]
    SeaBreezeOpticalBenchFeature: Type[SeaBreezeOpticalBenchFeature]
    SeaBreezePixelBinningFeature: Type[SeaBreezePixelBinningFeature]
    SeaBreezeRawUSBBusAccessFeature: Type[SeaBreezeRawUSBBusAccessFeature]
    SeaBreezeRevisionFeature: Type[SeaBreezeRevisionFeature]
    SeaBreezeShutterFeature: Type[SeaBreezeShutterFeature]
    SeaBreezeSpectrometerFeature: Type[SeaBreezeSpectrometerFeature]
    SeaBreezeSpectrumProcessingFeature: Type[SeaBreezeSpectrumProcessingFeature]
    SeaBreezeStrayLightCoefficientsFeature: Type[SeaBreezeStrayLightCoefficientsFeature]
    SeaBreezeStrobeLampFeature: Type[SeaBreezeStrobeLampFeature]
    SeaBreezeTemperatureFeature: Type[SeaBreezeTemperatureFeature]
    SeaBreezeThermoElectricFeature: Type[SeaBreezeThermoElectricFeature]
    SeaBreezeWifiConfigurationFeature: Type[SeaBreezeWifiConfigurationFeature]
